import type { AppRole } from "@/lib/appRole";

export const PERMISSIONS = {
  usersRead: "users.read",
  usersCreate: "users.create",
  usersUpdate: "users.update",
  usersPermissionsManage: "users.permissions.manage",
  usersActivate: "users.activate",
  settingsStoreRead: "settings.store.read",
  settingsStoreUpdate: "settings.store.update",
  branchesRead: "branches.read",
  branchesReadAll: "branches.read_all",
  customersRead: "customers.read",
  customersCreate: "customers.create",
  customersUpdate: "customers.update",
  customersBlacklist: "customers.blacklist",
  customersStatementRead: "customers.statement.read",
  quotesRead: "quotes.read",
  quotesCreate: "quotes.create",
  quotesUpdate: "quotes.update",
  quotesSend: "quotes.send",
  quotesRemind: "quotes.remind",
  quotesApprove: "quotes.approve",
  quotesConvert: "quotes.convert",
  quotesCrossBranch: "quotes.cross_branch",
  quotesJobsRun: "quotes.jobs.run",
  inventoryReadForQuotes: "inventory.read_for_quotes",
  inventoryCrossBranch: "inventory.cross_branch",
  salesReceiptsRead: "sales.receipts.read",
  salesReceiptsCrossBranch: "sales.receipts.cross_branch",
  salesNotesUpdate: "sales.notes.update",
  salesRefundsManage: "sales.refunds.manage",
  reportsDashboardRead: "reports.dashboard.read",
  reportsDashboardCrossBranch: "reports.dashboard.cross_branch",
  reportsFinanceRead: "reports.finance.read",
  reportsFinanceCrossBranch: "reports.finance.cross_branch",
  financeExpensesManage: "finance.expenses.manage",
  financeSupplierPaymentsManage: "finance.supplier_payments.manage",
  financePayablesRead: "finance.payables.read",
  catalogBrandsCreate: "catalog.brands.create",
  catalogCategoriesCreate: "catalog.categories.create",
  productsCreate: "products.create",
  productsUpdate: "products.update",
  productsArchive: "products.archive",
  componentsSearch: "components.search",
  componentsImport: "components.import",
  locationsCreate: "locations.create",
  stockAdjust: "stock.adjust",
  stockTransfersRead: "stock.transfers.read",
  stockTransfersManage: "stock.transfers.manage",
  suppliersCreate: "suppliers.create",
  purchaseOrdersCreate: "purchase_orders.create",
  purchaseOrdersReceive: "purchase_orders.receive",
  repairsCreate: "repairs.create",
  repairsRead: "repairs.read",
  repairsUpdate: "repairs.update",
  cashShiftsRead: "cash_shifts.read",
  cashShiftsManage: "cash_shifts.manage",
  hrRead: "hr.read",
  hrManage: "hr.manage",
  payrollRead: "payroll.read",
  payrollManage: "payroll.manage",
  payrollCrossBranch: "payroll.cross_branch",
  payrollOverrideManage: "payroll.override.manage",
  auditRead: "audit.read",
  loyaltyManage: "loyalty.manage",
  syncPreview: "sync.preview",
  syncMutate: "sync.mutate",
  syncResolve: "sync.resolve",
  syncForce: "sync.force",
  syncCrossBranch: "sync.cross_branch",
  elevationCodeIssue: "elevation.code.issue",
  elevationApprovalsRead: "elevation.approvals.read",
  elevationApprovalsResolve: "elevation.approvals.resolve",
  elevationSupervisorApprove: "elevation.supervisor.approve",
  integrationsEtaSubmit: "integrations.eta.submit",
  integrationsEtaLogsRead: "integrations.eta.logs.read",
  integrationsEtaRetry: "integrations.eta.retry",
  buildsRead: "builds.read",
  buildsCreate: "builds.create",
  buildsUpdate: "builds.update",
  promotionsRead: "promotions.read",
  promotionsManage: "promotions.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type PermissionGroup = {
  id: string;
  label: string;
  permissions: Array<{
    key: PermissionKey;
    label: string;
    description: string;
  }>;
};

export const ALL_PERMISSION_KEYS = Object.values(PERMISSIONS) as PermissionKey[];

export const PERMISSION_GROUPS: PermissionGroup[] = [
  {
    id: "users",
    label: "Users & admin",
    permissions: [
      { key: PERMISSIONS.usersRead, label: "View team", description: "Open the Team area and list staff accounts." },
      { key: PERMISSIONS.usersCreate, label: "Create users", description: "Create new staff accounts." },
      { key: PERMISSIONS.usersUpdate, label: "Edit users", description: "Update staff profile data and branch assignment." },
      { key: PERMISSIONS.usersPermissionsManage, label: "Manage permissions", description: "Grant or revoke permissions for other members." },
      { key: PERMISSIONS.usersActivate, label: "Activate/deactivate users", description: "Enable or disable staff access." },
    ],
  },
  {
    id: "sales",
    label: "Sales, customers & quotes",
    permissions: [
      { key: PERMISSIONS.customersRead, label: "View customers", description: "Search and open customer records." },
      { key: PERMISSIONS.customersCreate, label: "Create customers", description: "Create new customer profiles." },
      { key: PERMISSIONS.customersUpdate, label: "Edit customers", description: "Update customer details and balances." },
      { key: PERMISSIONS.customersBlacklist, label: "Blacklist customers", description: "Mark customers as blacklisted." },
      { key: PERMISSIONS.customersStatementRead, label: "View statements", description: "Generate customer statements." },
      { key: PERMISSIONS.quotesRead, label: "View quotes", description: "Read saved quotes." },
      { key: PERMISSIONS.quotesCreate, label: "Create quotes", description: "Create draft quotes." },
      { key: PERMISSIONS.quotesUpdate, label: "Edit quotes", description: "Update quote details and statuses." },
      { key: PERMISSIONS.quotesSend, label: "Send quotes", description: "Mark quotes as sent." },
      { key: PERMISSIONS.quotesRemind, label: "Send quote reminders", description: "Log manual quote reminders." },
      { key: PERMISSIONS.quotesApprove, label: "Approve quotes", description: "Approve sent quotes." },
      { key: PERMISSIONS.quotesConvert, label: "Convert quotes", description: "Convert approved quotes to sales." },
      { key: PERMISSIONS.quotesCrossBranch, label: "Use quotes across branches", description: "Work with quotes outside the assigned branch." },
      { key: PERMISSIONS.quotesJobsRun, label: "Run quote jobs", description: "Run reminder and expiry jobs." },
      { key: PERMISSIONS.inventoryReadForQuotes, label: "Browse inventory for quotes", description: "Search inventory while building quotes." },
      { key: PERMISSIONS.inventoryCrossBranch, label: "Browse inventory across branches", description: "Search quote inventory outside the assigned branch." },
      { key: PERMISSIONS.salesReceiptsRead, label: "View receipts", description: "List and inspect past receipts." },
      { key: PERMISSIONS.salesReceiptsCrossBranch, label: "View receipts across branches", description: "Inspect receipts outside the assigned branch." },
      { key: PERMISSIONS.salesNotesUpdate, label: "Edit invoice notes", description: "Update notes shown on invoice reprints." },
      { key: PERMISSIONS.salesRefundsManage, label: "Process refunds", description: "Create sale refunds and restock returned items." },
    ],
  },
  {
    id: "inventory",
    label: "Catalog & inventory",
    permissions: [
      { key: PERMISSIONS.branchesRead, label: "View branches", description: "Load branch options." },
      { key: PERMISSIONS.branchesReadAll, label: "View all branches", description: "See and select every branch." },
      { key: PERMISSIONS.catalogBrandsCreate, label: "Create brands", description: "Add catalog brands." },
      { key: PERMISSIONS.catalogCategoriesCreate, label: "Create categories", description: "Add catalog categories." },
      { key: PERMISSIONS.productsCreate, label: "Create products", description: "Add products to the catalog." },
      { key: PERMISSIONS.productsUpdate, label: "Edit products", description: "Update existing products." },
      { key: PERMISSIONS.productsArchive, label: "Archive products", description: "Disable products from active use." },
      { key: PERMISSIONS.componentsSearch, label: "Search components", description: "Search external component sources." },
      { key: PERMISSIONS.componentsImport, label: "Import components", description: "Import components into the catalog." },
      { key: PERMISSIONS.locationsCreate, label: "Create locations", description: "Create stock locations." },
      { key: PERMISSIONS.stockAdjust, label: "Adjust stock", description: "Perform stock adjustment operations." },
    ],
  },
  {
    id: "operations",
    label: "Operations",
    permissions: [
      { key: PERMISSIONS.suppliersCreate, label: "Create suppliers", description: "Add supplier records." },
      { key: PERMISSIONS.purchaseOrdersCreate, label: "Create purchase orders", description: "Create purchase orders." },
      { key: PERMISSIONS.purchaseOrdersReceive, label: "Receive purchase orders", description: "Record purchase-order receipts." },
      { key: PERMISSIONS.stockTransfersRead, label: "View stock transfers", description: "List stock transfers between branches." },
      { key: PERMISSIONS.stockTransfersManage, label: "Manage stock transfers", description: "Create, ship, and receive stock transfers." },
      { key: PERMISSIONS.repairsRead, label: "View repairs", description: "Read repair ticket details." },
      { key: PERMISSIONS.repairsCreate, label: "Create repairs", description: "Open new repair tickets." },
      { key: PERMISSIONS.repairsUpdate, label: "Update repairs", description: "Edit repair tickets." },
      { key: PERMISSIONS.buildsRead, label: "View PC build orders", description: "List and inspect build orders." },
      { key: PERMISSIONS.buildsCreate, label: "Create PC build orders", description: "Open new PC build orders." },
      { key: PERMISSIONS.buildsUpdate, label: "Update PC build orders", description: "Update build status and parts." },
      { key: PERMISSIONS.cashShiftsRead, label: "View cash shifts", description: "Inspect shift and cash-drawer records." },
      { key: PERMISSIONS.cashShiftsManage, label: "Manage cash shifts", description: "Open, reconcile, and close cash shifts." },
    ],
  },
  {
    id: "people",
    label: "People & payroll",
    permissions: [
      { key: PERMISSIONS.hrRead, label: "View HR", description: "Open employee, attendance, and leave records." },
      { key: PERMISSIONS.hrManage, label: "Manage HR", description: "Create employee profiles and update attendance or leave." },
      { key: PERMISSIONS.payrollRead, label: "View payroll", description: "Inspect payroll runs and salary history." },
      { key: PERMISSIONS.payrollManage, label: "Manage payroll", description: "Create payroll runs and update compensation." },
      { key: PERMISSIONS.payrollCrossBranch, label: "Cross-branch payroll", description: "Access payroll data across every branch." },
      { key: PERMISSIONS.payrollOverrideManage, label: "Payroll overrides", description: "Apply salary overrides and retroactive payroll edits." },
    ],
  },
  {
    id: "reporting",
    label: "Reporting & settings",
    permissions: [
      { key: PERMISSIONS.reportsDashboardRead, label: "View dashboard analytics", description: "Access dashboard insights and charts." },
      { key: PERMISSIONS.reportsDashboardCrossBranch, label: "View dashboard across branches", description: "Filter dashboard analytics by other branches." },
      { key: PERMISSIONS.reportsFinanceRead, label: "View finance", description: "Open finance reporting." },
      { key: PERMISSIONS.reportsFinanceCrossBranch, label: "View finance across branches", description: "Filter finance reporting by other branches." },
      { key: PERMISSIONS.financeExpensesManage, label: "Record expenses", description: "Create operating expense entries." },
      { key: PERMISSIONS.financeSupplierPaymentsManage, label: "Record supplier payments", description: "Log cash paid to suppliers." },
      { key: PERMISSIONS.financePayablesRead, label: "View payables", description: "Open the payables workspace and aging." },
      { key: PERMISSIONS.auditRead, label: "View audit trail", description: "Inspect sensitive activity and change history." },
      { key: PERMISSIONS.loyaltyManage, label: "Manage loyalty", description: "Configure loyalty earning and redemption settings." },
      { key: PERMISSIONS.promotionsRead, label: "View promotions", description: "List promotions, coupons, and price lists." },
      { key: PERMISSIONS.promotionsManage, label: "Manage promotions", description: "Create and modify promotions, coupons, and price lists." },
      { key: PERMISSIONS.settingsStoreRead, label: "View settings", description: "Read store settings." },
      { key: PERMISSIONS.settingsStoreUpdate, label: "Edit settings", description: "Update store settings." },
    ],
  },
  {
    id: "platform",
    label: "Sync, elevation & integrations",
    permissions: [
      { key: PERMISSIONS.syncPreview, label: "Preview sync", description: "Preview sync conflicts and payloads." },
      { key: PERMISSIONS.syncMutate, label: "Run sync", description: "Send sync mutations." },
      { key: PERMISSIONS.syncResolve, label: "Resolve sync conflicts", description: "Resolve sync conflicts." },
      { key: PERMISSIONS.syncForce, label: "Force sync", description: "Force local sync actions." },
      { key: PERMISSIONS.syncCrossBranch, label: "Sync across branches", description: "Operate sync outside the assigned branch." },
      { key: PERMISSIONS.elevationCodeIssue, label: "Issue elevation code", description: "Generate one-time elevation codes." },
      { key: PERMISSIONS.elevationApprovalsRead, label: "View elevation approvals", description: "Review pending elevation approvals." },
      { key: PERMISSIONS.elevationApprovalsResolve, label: "Resolve elevation approvals", description: "Approve or deny elevation requests." },
      { key: PERMISSIONS.elevationSupervisorApprove, label: "Supervisor elevation", description: "Act as a supervisor for restricted actions." },
      { key: PERMISSIONS.integrationsEtaSubmit, label: "Submit ETA invoices", description: "Send ETA invoice requests." },
      { key: PERMISSIONS.integrationsEtaLogsRead, label: "View ETA logs", description: "Read ETA invoice logs." },
      { key: PERMISSIONS.integrationsEtaRetry, label: "Retry ETA invoices", description: "Retry ETA invoice submissions." },
    ],
  },
];

function uniquePermissions(permissions: Iterable<PermissionKey>): PermissionKey[] {
  return Array.from(new Set(permissions)).sort((a, b) => a.localeCompare(b));
}

export const LEGACY_ROLE_PERMISSION_PRESETS: Record<AppRole, PermissionKey[]> = {
  OWNER: uniquePermissions(ALL_PERMISSION_KEYS),
  MANAGER: uniquePermissions([
    PERMISSIONS.usersRead,
    PERMISSIONS.usersCreate,
    PERMISSIONS.usersUpdate,
    PERMISSIONS.usersPermissionsManage,
    PERMISSIONS.usersActivate,
    PERMISSIONS.settingsStoreRead,
    PERMISSIONS.settingsStoreUpdate,
    PERMISSIONS.branchesRead,
    PERMISSIONS.branchesReadAll,
    PERMISSIONS.customersRead,
    PERMISSIONS.customersCreate,
    PERMISSIONS.customersUpdate,
    PERMISSIONS.customersBlacklist,
    PERMISSIONS.customersStatementRead,
    PERMISSIONS.quotesRead,
    PERMISSIONS.quotesCreate,
    PERMISSIONS.quotesUpdate,
    PERMISSIONS.quotesSend,
    PERMISSIONS.quotesRemind,
    PERMISSIONS.quotesApprove,
    PERMISSIONS.quotesConvert,
    PERMISSIONS.quotesCrossBranch,
    PERMISSIONS.quotesJobsRun,
    PERMISSIONS.inventoryReadForQuotes,
    PERMISSIONS.inventoryCrossBranch,
    PERMISSIONS.salesReceiptsRead,
    PERMISSIONS.salesReceiptsCrossBranch,
    PERMISSIONS.salesNotesUpdate,
    PERMISSIONS.salesRefundsManage,
    PERMISSIONS.reportsDashboardRead,
    PERMISSIONS.reportsDashboardCrossBranch,
    PERMISSIONS.reportsFinanceRead,
    PERMISSIONS.reportsFinanceCrossBranch,
    PERMISSIONS.financeExpensesManage,
    PERMISSIONS.financeSupplierPaymentsManage,
    PERMISSIONS.financePayablesRead,
    PERMISSIONS.catalogBrandsCreate,
    PERMISSIONS.catalogCategoriesCreate,
    PERMISSIONS.productsCreate,
    PERMISSIONS.productsUpdate,
    PERMISSIONS.productsArchive,
    PERMISSIONS.componentsSearch,
    PERMISSIONS.componentsImport,
    PERMISSIONS.locationsCreate,
    PERMISSIONS.stockAdjust,
    PERMISSIONS.stockTransfersRead,
    PERMISSIONS.stockTransfersManage,
    PERMISSIONS.suppliersCreate,
    PERMISSIONS.purchaseOrdersCreate,
    PERMISSIONS.purchaseOrdersReceive,
    PERMISSIONS.repairsRead,
    PERMISSIONS.repairsCreate,
    PERMISSIONS.repairsUpdate,
    PERMISSIONS.cashShiftsRead,
    PERMISSIONS.cashShiftsManage,
    PERMISSIONS.buildsRead,
    PERMISSIONS.buildsCreate,
    PERMISSIONS.buildsUpdate,
    PERMISSIONS.promotionsRead,
    PERMISSIONS.promotionsManage,
    PERMISSIONS.hrRead,
    PERMISSIONS.hrManage,
    PERMISSIONS.payrollRead,
    PERMISSIONS.payrollManage,
    PERMISSIONS.auditRead,
    PERMISSIONS.loyaltyManage,
    PERMISSIONS.syncPreview,
    PERMISSIONS.syncMutate,
    PERMISSIONS.syncResolve,
    PERMISSIONS.syncForce,
    PERMISSIONS.syncCrossBranch,
    PERMISSIONS.elevationCodeIssue,
    PERMISSIONS.elevationApprovalsRead,
    PERMISSIONS.elevationApprovalsResolve,
    PERMISSIONS.elevationSupervisorApprove,
    PERMISSIONS.payrollCrossBranch,
    PERMISSIONS.payrollOverrideManage,
    PERMISSIONS.integrationsEtaSubmit,
    PERMISSIONS.integrationsEtaLogsRead,
    PERMISSIONS.integrationsEtaRetry,
  ]),
  CASHIER: uniquePermissions([
    PERMISSIONS.settingsStoreRead,
    PERMISSIONS.branchesRead,
    PERMISSIONS.customersRead,
    PERMISSIONS.customersCreate,
    PERMISSIONS.customersUpdate,
    PERMISSIONS.customersStatementRead,
    PERMISSIONS.quotesRead,
    PERMISSIONS.quotesCreate,
    PERMISSIONS.quotesUpdate,
    PERMISSIONS.quotesSend,
    PERMISSIONS.quotesRemind,
    PERMISSIONS.quotesConvert,
    PERMISSIONS.inventoryReadForQuotes,
    PERMISSIONS.salesReceiptsRead,
    PERMISSIONS.reportsDashboardRead,
    PERMISSIONS.reportsFinanceRead,
    PERMISSIONS.componentsSearch,
    PERMISSIONS.repairsRead,
    PERMISSIONS.repairsCreate,
    PERMISSIONS.buildsRead,
    PERMISSIONS.buildsCreate,
    PERMISSIONS.cashShiftsRead,
    PERMISSIONS.cashShiftsManage,
    PERMISSIONS.promotionsRead,
    PERMISSIONS.syncPreview,
    PERMISSIONS.syncMutate,
    PERMISSIONS.syncResolve,
    PERMISSIONS.syncForce,
  ]),
  WAREHOUSE: uniquePermissions([
    PERMISSIONS.settingsStoreRead,
    PERMISSIONS.branchesRead,
    PERMISSIONS.customersRead,
    PERMISSIONS.customersStatementRead,
    PERMISSIONS.quotesRead,
    PERMISSIONS.inventoryReadForQuotes,
    PERMISSIONS.salesReceiptsRead,
    PERMISSIONS.reportsDashboardRead,
    PERMISSIONS.reportsFinanceRead,
    PERMISSIONS.catalogBrandsCreate,
    PERMISSIONS.catalogCategoriesCreate,
    PERMISSIONS.productsCreate,
    PERMISSIONS.productsUpdate,
    PERMISSIONS.productsArchive,
    PERMISSIONS.componentsSearch,
    PERMISSIONS.componentsImport,
    PERMISSIONS.locationsCreate,
    PERMISSIONS.stockAdjust,
    PERMISSIONS.stockTransfersRead,
    PERMISSIONS.stockTransfersManage,
    PERMISSIONS.suppliersCreate,
    PERMISSIONS.purchaseOrdersCreate,
    PERMISSIONS.purchaseOrdersReceive,
    PERMISSIONS.repairsRead,
    PERMISSIONS.repairsCreate,
    PERMISSIONS.repairsUpdate,
    PERMISSIONS.syncPreview,
    PERMISSIONS.syncMutate,
    PERMISSIONS.syncResolve,
    PERMISSIONS.syncForce,
  ]),
};

export function isPermissionKey(value: string): value is PermissionKey {
  return (ALL_PERMISSION_KEYS as string[]).includes(value);
}

export function normalizePermissions(permissions: readonly string[] | null | undefined): PermissionKey[] {
  return uniquePermissions((permissions ?? []).filter(isPermissionKey));
}

export function hasPermission(
  permissions: readonly string[] | null | undefined,
  permission: PermissionKey,
): boolean {
  return normalizePermissions(permissions).includes(permission);
}

export function hasAnyPermission(
  permissions: readonly string[] | null | undefined,
  required: readonly PermissionKey[],
): boolean {
  if (required.length === 0) return true;
  const normalized = new Set(normalizePermissions(permissions));
  return required.some((permission) => normalized.has(permission));
}

export function hasAllPermissions(
  permissions: readonly string[] | null | undefined,
  required: readonly PermissionKey[],
): boolean {
  const normalized = new Set(normalizePermissions(permissions));
  return required.every((permission) => normalized.has(permission));
}

export function legacyRoleToPermissions(role: AppRole | null | undefined): PermissionKey[] {
  if (!role) return [];
  return [...LEGACY_ROLE_PERMISSION_PRESETS[role]];
}

export function describePermissionCount(count: number): string {
  if (count === 1) return "1 permission";
  return `${count} permissions`;
}
